language: cpp
services:
    - docker
git:
    depth: false
dist: xenial
sudo: required
matrix:
    include:
        - env: TARGET_OS=debian.stretch
        - env: TARGET_OS=ubuntu.bionic
        - env: TARGET_OS=ubuntu.xenial
        - env: TARGET_OS=cross.win32
        - env: TARGET_OS=cross.win64
        - env: TARGET_OS=centos.73
        - env: TARGET_OS=fedora.28
        - env: TARGET_OS=opensuse.42.3
        - env: TARGET_OS=opensuse.15.0
        - env: TARGET_OS=sast
script:
    - wget http://archive.ubuntu.com/ubuntu/pool/main/libs/libseccomp/libseccomp2_2.3.3-3ubuntu1_amd64.deb && sudo dpkg -i libseccomp2*deb
    - docker pull veyon/travis.${TRAVIS_OS_NAME}.${TARGET_OS}:4.1 || docker build -t veyon/travis.${TRAVIS_OS_NAME}.${TARGET_OS}:4.1 ${TRAVIS_BUILD_DIR}/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}/
    - docker run -v ${TRAVIS_BUILD_DIR}:/veyon:rw veyon/travis.${TRAVIS_OS_NAME}.${TARGET_OS}:4.1 /bin/sh /veyon/.travis/${TRAVIS_OS_NAME}.${TARGET_OS}/script.sh
deploy:
    provider: releases
    api_key:
        secure: Hvax0pT56HkHHDFhNnCoMIxhTCRZ2eHSK1kf0Lw91pX/UPsexkhtFm9qck2siyyAW5IDaXMWCvbJmD5f8TXNZV5d65NQ9lc0OtUdl/os6Te3LhIbNjdywKQQknWkZxoX+blXr1VCoRUjvruxwt2Q9yIjMJn40cMh8bnQPAx1VNdCAiGNSIb8vFBmTbv9a6GTkQ3xHjlSrtCXoeq3/AZ3OqrRtXLe5uS+TquZBZv4gS908+TaveSfRUBVFB/XPvNKHVdFPYSkQUz3i0k+/ZV+7gWGEHLk2nXcKRe+6tjrsQyhvqTbyOUiQxjsWHHW0dql67ZFmvQR31RM6l/IO3QhBNu1Qotu7IyxKExE7Wn5+RiyLYOA80RoyK09uAJA7T/MyvoY2QH1dWYQEi6kJQdK7A/g51zJJosILaZuokvmF19cjTu7MC0eMkAhhTWB79JRBLg+6DOskCesWfFf7xuCqt4XqONOjWb2N1vSgH0EkkAN4w2jlO/utX9f2bQTC6sOgW57V+/1yD7rKAj0QdI+eJSuuR0azId+UtBEaSefIuGhR7qw+vQ/GZQ27uz4GZ2NalD1mp0wt0wfx+p2TW2XC03uMO1j2ZY3ve8wT+sFlbEMKmwxC3ObRpM14ez2/EIAotauZ0HKDRm/AzvpShz8o9geChxZTuez06frt6Zx7fo=
    repo: veyon/veyon
    skip_cleanup: true
    file_glob: true
    file: "veyon*"
    on:
        tags: true
        all_branches: true
